on:
  - push

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    uses: cloud-cli/workflows/.github/workflows/docker-ghcr-python.yml@main
    with:
      name: cloudy-apps/js2py